name: Checkstyle
description: Run checkstyle
inputs:
  sourcePath:
    description: Root directory for sources
    required: true
  configFile:
    description: Config path for checkstyle
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sourcePath }}
    - ${{ inputs.configFile }}
branding:
  icon: code
  color: white