name: checkstyle
on: 
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkstyle process
      uses: desckapg-weastur-dev/eol_bot/.github/actions/checkstyle@v0.2.1
      with:
        sourcePath: 'src/main/java'
        configFile: 'config/checkstyle/sun_checks.xml'
  
