name: checkstyle

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        checkstyle_config: 'config/checkstyle/sun_checks.xml'
        reporter: github-pr-review
        level: warning
